# 要开始使用 Dependabot 版本更新，您需要指定要更新的
# 软件包生态系统以及软件包清单文件的位置。
# 有关所有配置选项，请参阅文档：
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"
